/**
 * Effect Definitions
 *
 * All available video effects organized by category.
 * Each definition describes metadata + default parameters.
 * The actual rendering logic lives in the effects engine.
 */

import type { EffectDefinition } from "@/types/effects";

// ── Color & Cinematic Effects ──

const colorEffects: EffectDefinition[] = [
	{
		id: "color-grading",
		type: "color-grading",
		name: "AI Color Grading",
		category: "color",
		description: "Automatic cinematic color grading",
		icon: "🎨",
		defaultIntensity: 0.6,
		minIntensity: 0,
		maxIntensity: 1,
		parameters: [
			{
				key: "temperature",
				label: "Temperature",
				type: "number",
				defaultValue: 0,
				min: -1,
				max: 1,
				step: 0.05,
			},
			{
				key: "tint",
				label: "Tint",
				type: "number",
				defaultValue: 0,
				min: -1,
				max: 1,
				step: 0.05,
			},
		],
	},
	{
		id: "cinematic-lut",
		type: "cinematic-lut",
		name: "Cinematic LUT",
		category: "color",
		description: "Hollywood-style color look-up table",
		icon: "🎬",
		defaultIntensity: 0.7,
		minIntensity: 0,
		maxIntensity: 1,
		parameters: [
			{
				key: "style",
				label: "LUT Style",
				type: "select",
				defaultValue: "blockbuster",
				options: [
					{ label: "Blockbuster", value: "blockbuster" },
					{ label: "Indie Film", value: "indie" },
					{ label: "Noir", value: "noir" },
					{ label: "Sci-Fi", value: "scifi" },
				],
			},
		],
	},
	{
		id: "golden-hour",
		type: "golden-hour",
		name: "Golden Hour",
		category: "color",
		description: "Warm golden hour sun enhancement",
		icon: "🌅",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "night-cinematic",
		type: "night-cinematic",
		name: "Night Cinematic",
		category: "color",
		description: "Cool blue cinematic night look",
		icon: "🌙",
		defaultIntensity: 0.6,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "vintage-film",
		type: "vintage-film",
		name: "Vintage Film",
		category: "color",
		description: "Retro vintage film color palette",
		icon: "📼",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "film-grain",
		type: "film-grain",
		name: "Film Grain",
		category: "color",
		description: "Organic film grain texture overlay",
		icon: "🎞️",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "hdr-enhancement",
		type: "hdr-enhancement",
		name: "HDR Enhancement",
		category: "color",
		description: "High dynamic range boost",
		icon: "🌈",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "teal-orange",
		type: "teal-orange",
		name: "Teal & Orange",
		category: "color",
		description: "Hollywood blockbuster teal & orange look",
		icon: "🎥",
		defaultIntensity: 0.6,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "fade-film",
		type: "fade-film",
		name: "Fade Film",
		category: "color",
		description: "Faded, washed-out film aesthetic",
		icon: "🌫️",
		defaultIntensity: 0.4,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "warm-tone",
		type: "warm-tone",
		name: "Warm Tone",
		category: "color",
		description: "Warm color temperature shift",
		icon: "🔥",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "cool-tone",
		type: "cool-tone",
		name: "Cool Tone",
		category: "color",
		description: "Cool blue color temperature shift",
		icon: "❄️",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "grayscale",
		type: "grayscale",
		name: "Black & White",
		category: "color",
		description: "Classic monochrome look",
		icon: "⬛",
		defaultIntensity: 1.0,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "sepia",
		type: "sepia",
		name: "Sepia Vintage",
		category: "color",
		description: "Warm sepia tone",
		icon: "📜",
		defaultIntensity: 1.0,
		minIntensity: 0,
		maxIntensity: 1,
	},
];

// ── Visual Effects (VFX) ──

const vfxEffects: EffectDefinition[] = [
	{
		id: "glitch",
		type: "glitch",
		name: "Glitch",
		category: "vfx",
		description: "Digital glitch distortion",
		icon: "⚡",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
		parameters: [
			{
				key: "speed",
				label: "Speed",
				type: "number",
				defaultValue: 0.5,
				min: 0.1,
				max: 2,
				step: 0.1,
			},
		],
	},
	{
		id: "lens-flare",
		type: "lens-flare",
		name: "Lens Flare",
		category: "vfx",
		description: "Cinematic lens flare overlay",
		icon: "💡",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
		parameters: [
			{
				key: "positionX",
				label: "Position X",
				type: "number",
				defaultValue: 0.7,
				min: 0,
				max: 1,
				step: 0.05,
			},
			{
				key: "positionY",
				label: "Position Y",
				type: "number",
				defaultValue: 0.3,
				min: 0,
				max: 1,
				step: 0.05,
			},
		],
	},
	{
		id: "light-leaks",
		type: "light-leaks",
		name: "Light Leaks",
		category: "vfx",
		description: "Warm light leak overlay effect",
		icon: "🌈",
		defaultIntensity: 0.4,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "impact-flash",
		type: "impact-flash",
		name: "Impact Flash",
		category: "vfx",
		description: "Bright white impact flash",
		icon: "💥",
		defaultIntensity: 0.8,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "ripple",
		type: "ripple",
		name: "Ripple Effect",
		category: "vfx",
		description: "Water ripple distortion",
		icon: "🌊",
		defaultIntensity: 0.4,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "warp-distortion",
		type: "warp-distortion",
		name: "Warp Distortion",
		category: "vfx",
		description: "Spatial warp and distortion",
		icon: "🌪️",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "sparkle",
		type: "sparkle",
		name: "Sparkle Particles",
		category: "vfx",
		description: "Sparkle and particle overlay",
		icon: "🌟",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "fog-overlay",
		type: "fog-overlay",
		name: "Fog Overlay",
		category: "vfx",
		description: "Atmospheric fog/mist overlay",
		icon: "🌫️",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "dream-glow",
		type: "dream-glow",
		name: "Dream Glow",
		category: "vfx",
		description: "Soft dreamy glow effect",
		icon: "💫",
		defaultIntensity: 0.4,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "rgb-split",
		type: "rgb-split",
		name: "RGB Split",
		category: "vfx",
		description: "Chromatic aberration RGB channel split",
		icon: "🔴",
		defaultIntensity: 0.4,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "vignette",
		type: "vignette",
		name: "Vignette",
		category: "vfx",
		description: "Dark edges vignette",
		icon: "🔲",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "pixelate",
		type: "pixelate",
		name: "Pixelate",
		category: "vfx",
		description: "Pixelation mosaic effect",
		icon: "🟩",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
];

// ── Motion Effects ──

const motionEffects: EffectDefinition[] = [
	{
		id: "zoom-in",
		type: "zoom-in",
		name: "Zoom In",
		category: "motion",
		description: "Gradual zoom into the frame",
		icon: "🔎",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "zoom-out",
		type: "zoom-out",
		name: "Zoom Out",
		category: "motion",
		description: "Gradual zoom out from the frame",
		icon: "🔍",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "ken-burns",
		type: "ken-burns",
		name: "Ken Burns",
		category: "motion",
		description: "Slow pan and zoom (photo animation)",
		icon: "📷",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
		parameters: [
			{
				key: "direction",
				label: "Direction",
				type: "select",
				defaultValue: "top-left-to-bottom-right",
				options: [
					{ label: "Top-Left → Bottom-Right", value: "top-left-to-bottom-right" },
					{ label: "Bottom-Right → Top-Left", value: "bottom-right-to-top-left" },
					{ label: "Center Out", value: "center-out" },
					{ label: "Random", value: "random" },
				],
			},
		],
	},
	{
		id: "camera-shake",
		type: "camera-shake",
		name: "Camera Shake",
		category: "motion",
		description: "Handheld camera shake",
		icon: "📹",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "speed-ramp",
		type: "speed-ramp",
		name: "Speed Ramp",
		category: "motion",
		description: "Smooth speed ramp up/down",
		icon: "⏩",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
		parameters: [
			{
				key: "rampType",
				label: "Ramp Type",
				type: "select",
				defaultValue: "up-down",
				options: [
					{ label: "Speed Up → Slow Down", value: "up-down" },
					{ label: "Slow Down → Speed Up", value: "down-up" },
					{ label: "Speed Up", value: "up" },
					{ label: "Slow Down", value: "down" },
				],
			},
		],
	},
	{
		id: "parallax",
		type: "parallax",
		name: "Parallax",
		category: "motion",
		description: "Depth-based parallax movement",
		icon: "🏔️",
		defaultIntensity: 0.3,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "dolly-zoom",
		type: "dolly-zoom",
		name: "Dolly Zoom",
		category: "motion",
		description: "Hitchcock vertigo dolly zoom",
		icon: "🎥",
		defaultIntensity: 0.4,
		minIntensity: 0,
		maxIntensity: 1,
	},
];

// ── AI Smart Effects ──

const aiEffects: EffectDefinition[] = [
	{
		id: "ai-background-blur",
		type: "ai-background-blur",
		name: "AI Background Blur",
		category: "ai",
		description: "AI-powered background blur with subject detection",
		icon: "👤",
		defaultIntensity: 0.6,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "ai-depth-of-field",
		type: "ai-depth-of-field",
		name: "AI Depth of Field",
		category: "ai",
		description: "Cinematic depth of field from AI depth map",
		icon: "📸",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "ai-subject-highlight",
		type: "ai-subject-highlight",
		name: "AI Subject Highlight",
		category: "ai",
		description: "Highlight and enhance the main subject",
		icon: "🧍",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "ai-auto-subtitle",
		type: "ai-auto-subtitle",
		name: "Auto Subtitle Animation",
		category: "ai",
		description: "Animated subtitles synced to speech",
		icon: "🎤",
		defaultIntensity: 1.0,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "beat-sync-effects",
		type: "beat-sync-effects",
		name: "Beat Sync Effects",
		category: "ai",
		description: "Auto-apply effects on music beats",
		icon: "🎶",
		defaultIntensity: 0.6,
		minIntensity: 0,
		maxIntensity: 1,
	},
];

// ── Pro Effects ──

const proEffects: EffectDefinition[] = [
	{
		id: "blur-sm",
		type: "blur",
		name: "Slight Blur",
		category: "pro",
		description: "Light gaussian blur",
		icon: "🌁",
		defaultIntensity: 0.2,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "blur-lg",
		type: "blur",
		name: "Heavy Blur",
		category: "pro",
		description: "Strong gaussian blur",
		icon: "🌁",
		defaultIntensity: 0.8,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "brightness-up",
		type: "brightness",
		name: "Brighten",
		category: "pro",
		description: "Increase brightness",
		icon: "☀️",
		defaultIntensity: 0.75,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "contrast-up",
		type: "contrast",
		name: "High Contrast",
		category: "pro",
		description: "Increase contrast",
		icon: "🌓",
		defaultIntensity: 0.75,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "sharpen",
		type: "sharpen",
		name: "Sharpen",
		category: "pro",
		description: "Sharpen image details",
		icon: "🔪",
		defaultIntensity: 0.5,
		minIntensity: 0,
		maxIntensity: 1,
	},
	{
		id: "motion-blur",
		type: "motion-blur",
		name: "Motion Blur",
		category: "pro",
		description: "Directional motion blur",
		icon: "💨",
		defaultIntensity: 0.4,
		minIntensity: 0,
		maxIntensity: 1,
	},
];

// ── All Effects Registry ──

export const ALL_EFFECTS: EffectDefinition[] = [
	...colorEffects,
	...vfxEffects,
	...motionEffects,
	...aiEffects,
	...proEffects,
];

export const EFFECT_MAP = new Map(ALL_EFFECTS.map((effect) => [effect.id, effect]));

export function getEffectById(id: string): EffectDefinition | undefined {
	return EFFECT_MAP.get(id);
}

export function getEffectsByCategory(category: string): EffectDefinition[] {
	return ALL_EFFECTS.filter((effect) => effect.category === category);
}
