/**
 * Transition Definitions
 *
 * All available video transitions organized by category.
 * Each definition describes metadata + defaults.
 * The actual rendering logic lives in the transitions engine.
 */

import type { TransitionDefinition } from "@/types/effects";

// ── Basic Transitions ──

const basicTransitions: TransitionDefinition[] = [
	{
		id: "fade",
		type: "fade",
		name: "Fade",
		category: "basic",
		description: "Smooth fade in/out",
		icon: "🌑",
		defaultDuration: 0.8,
		minDuration: 0.1,
		maxDuration: 3.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "cross-dissolve",
		type: "cross-dissolve",
		name: "Cross Dissolve",
		category: "basic",
		description: "Blend two clips together",
		icon: "✨",
		defaultDuration: 1.0,
		minDuration: 0.2,
		maxDuration: 3.0,
		supportedDirections: ["both"],
	},
	{
		id: "dip-to-black",
		type: "dip-to-black",
		name: "Dip to Black",
		category: "basic",
		description: "Fade through black between clips",
		icon: "⬛",
		defaultDuration: 1.0,
		minDuration: 0.2,
		maxDuration: 3.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "dip-to-white",
		type: "dip-to-white",
		name: "Dip to White",
		category: "basic",
		description: "Fade through white between clips",
		icon: "⬜",
		defaultDuration: 1.0,
		minDuration: 0.2,
		maxDuration: 3.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "wipe",
		type: "wipe",
		name: "Wipe",
		category: "basic",
		description: "Directional wipe transition",
		icon: "➡️",
		defaultDuration: 0.8,
		minDuration: 0.2,
		maxDuration: 2.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "slide",
		type: "slide",
		name: "Slide",
		category: "basic",
		description: "Slide in/out from edge",
		icon: "📐",
		defaultDuration: 0.6,
		minDuration: 0.2,
		maxDuration: 2.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "push",
		type: "push",
		name: "Push",
		category: "basic",
		description: "Push one clip off while next slides in",
		icon: "👉",
		defaultDuration: 0.6,
		minDuration: 0.2,
		maxDuration: 2.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "crossfade",
		type: "crossfade",
		name: "Crossfade",
		category: "basic",
		description: "Audio and video crossfade",
		icon: "🔄",
		defaultDuration: 1.0,
		minDuration: 0.2,
		maxDuration: 3.0,
		supportedDirections: ["both"],
	},
];

// ── Cinematic Transitions ──

const cinematicTransitions: TransitionDefinition[] = [
	{
		id: "whip-pan",
		type: "whip-pan",
		name: "Whip Pan",
		category: "cinematic",
		description: "Fast horizontal motion blur whip",
		icon: "💨",
		defaultDuration: 0.4,
		minDuration: 0.1,
		maxDuration: 1.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "zoom-transition",
		type: "zoom-transition",
		name: "Zoom Transition",
		category: "cinematic",
		description: "Zoom in/out to reveal next clip",
		icon: "🔎",
		defaultDuration: 0.5,
		minDuration: 0.2,
		maxDuration: 1.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "spin-transition",
		type: "spin-transition",
		name: "Spin Transition",
		category: "cinematic",
		description: "Rotation spin between clips",
		icon: "🔄",
		defaultDuration: 0.6,
		minDuration: 0.2,
		maxDuration: 1.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "blur-transition",
		type: "blur-transition",
		name: "Blur Transition",
		category: "cinematic",
		description: "Blur out and into next clip",
		icon: "🌫️",
		defaultDuration: 0.6,
		minDuration: 0.2,
		maxDuration: 2.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "camera-pan",
		type: "camera-pan",
		name: "Camera Pan",
		category: "cinematic",
		description: "Simulated camera pan between clips",
		icon: "🎥",
		defaultDuration: 0.8,
		minDuration: 0.3,
		maxDuration: 2.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "flash-transition",
		type: "flash-transition",
		name: "Flash Transition",
		category: "cinematic",
		description: "Bright flash cutting to next clip",
		icon: "⚡",
		defaultDuration: 0.3,
		minDuration: 0.1,
		maxDuration: 1.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "warp-transition",
		type: "warp-transition",
		name: "Warp Transition",
		category: "cinematic",
		description: "Space-warp distortion transition",
		icon: "🌀",
		defaultDuration: 0.5,
		minDuration: 0.2,
		maxDuration: 1.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "light-leak-transition",
		type: "light-leak-transition",
		name: "Light Leak Transition",
		category: "cinematic",
		description: "Warm light leak between clips",
		icon: "🌅",
		defaultDuration: 0.8,
		minDuration: 0.3,
		maxDuration: 2.0,
		supportedDirections: ["in", "out", "both"],
	},
];

// ── Viral / Social Media Transitions ──

const viralTransitions: TransitionDefinition[] = [
	{
		id: "glitch-transition",
		type: "glitch-transition",
		name: "Glitch",
		category: "viral",
		description: "Digital glitch distortion cut",
		icon: "⚡",
		defaultDuration: 0.3,
		minDuration: 0.1,
		maxDuration: 1.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "mask-transition",
		type: "mask-transition",
		name: "Mask Transition",
		category: "viral",
		description: "Shape mask reveal transition",
		icon: "🎭",
		defaultDuration: 0.6,
		minDuration: 0.2,
		maxDuration: 1.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "liquid-morph",
		type: "liquid-morph",
		name: "Liquid Morph",
		category: "viral",
		description: "Fluid liquid morphing between clips",
		icon: "🫧",
		defaultDuration: 0.6,
		minDuration: 0.2,
		maxDuration: 1.5,
		supportedDirections: ["both"],
	},
	{
		id: "shape-morph",
		type: "shape-morph",
		name: "Shape Morph",
		category: "viral",
		description: "Geometric shape morph transition",
		icon: "🔷",
		defaultDuration: 0.5,
		minDuration: 0.2,
		maxDuration: 1.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "pixel-sort",
		type: "pixel-sort",
		name: "Pixel Sort",
		category: "viral",
		description: "Glitch art pixel sorting effect",
		icon: "📊",
		defaultDuration: 0.5,
		minDuration: 0.2,
		maxDuration: 1.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "rgb-split-transition",
		type: "rgb-split-transition",
		name: "RGB Split",
		category: "viral",
		description: "RGB channel split transition",
		icon: "🔴",
		defaultDuration: 0.3,
		minDuration: 0.1,
		maxDuration: 1.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "frame-smash",
		type: "frame-smash",
		name: "Frame Smash",
		category: "viral",
		description: "Frame-breaking smash cut",
		icon: "💥",
		defaultDuration: 0.3,
		minDuration: 0.1,
		maxDuration: 1.0,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "swipe-match",
		type: "swipe-match",
		name: "Swipe Match",
		category: "viral",
		description: "Social-media swipe match cut",
		icon: "👆",
		defaultDuration: 0.4,
		minDuration: 0.1,
		maxDuration: 1.0,
		supportedDirections: ["in", "out", "both"],
	},
];

// ── Beat Sync Transitions ──

const beatTransitions: TransitionDefinition[] = [
	{
		id: "beat-flash",
		type: "beat-flash",
		name: "Beat Flash",
		category: "beat",
		description: "White flash on beat",
		icon: "💥",
		defaultDuration: 0.15,
		minDuration: 0.05,
		maxDuration: 0.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "beat-zoom",
		type: "beat-zoom",
		name: "Beat Zoom",
		category: "beat",
		description: "Quick zoom pulse on beat",
		icon: "🔎",
		defaultDuration: 0.2,
		minDuration: 0.05,
		maxDuration: 0.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "beat-glitch",
		type: "beat-glitch",
		name: "Beat Glitch",
		category: "beat",
		description: "Glitch effect on beat",
		icon: "⚡",
		defaultDuration: 0.15,
		minDuration: 0.05,
		maxDuration: 0.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "beat-shake",
		type: "beat-shake",
		name: "Beat Shake",
		category: "beat",
		description: "Camera shake on beat",
		icon: "📳",
		defaultDuration: 0.2,
		minDuration: 0.05,
		maxDuration: 0.5,
		supportedDirections: ["in", "out", "both"],
	},
	{
		id: "beat-cut",
		type: "beat-cut",
		name: "Beat Cut",
		category: "beat",
		description: "Hard cut synced to beat",
		icon: "✂️",
		defaultDuration: 0.05,
		minDuration: 0.02,
		maxDuration: 0.2,
		supportedDirections: ["both"],
	},
];

// ── All Transitions Registry ──

export const ALL_TRANSITIONS: TransitionDefinition[] = [
	...basicTransitions,
	...cinematicTransitions,
	...viralTransitions,
	...beatTransitions,
];

export const TRANSITION_MAP = new Map(
	ALL_TRANSITIONS.map((transition) => [transition.id, transition]),
);

export function getTransitionById(id: string): TransitionDefinition | undefined {
	return TRANSITION_MAP.get(id);
}

export function getTransitionsByCategory(category: string): TransitionDefinition[] {
	return ALL_TRANSITIONS.filter((transition) => transition.category === category);
}
