export const TEMPLATE_CATEGORIES = [
	{ id: "all", label: "All" },
	{ id: "featured", label: "Featured: UNI-1" },
	{ id: "reels", label: "Reels & Shorts" },
	{ id: "branding", label: "Branding" },
	{ id: "filmmaking", label: "Filmmaking" },
	{ id: "marketing", label: "Marketing" },
	{ id: "product-design", label: "Product Design" },
] as const;

export type TemplateCategoryId = (typeof TEMPLATE_CATEGORIES)[number]["id"];

export interface Template {
	id: string;
	name: string;
	nameHighlight: string;
	categories: TemplateCategoryId[];
	type: "image" | "video";
	prompt: string;
	gradient: string;
}

export const TEMPLATES: Template[] = [
	{
		id: "action-figures",
		name: "Action",
		nameHighlight: "Figures",
		categories: ["featured", "product-design"],
		type: "image",
		prompt: "Create action figure product shots with dynamic poses and dramatic lighting",
		gradient: "from-amber-800 to-orange-600",
	},
	{
		id: "age-transformation",
		name: "Age",
		nameHighlight: "Transformation",
		categories: ["featured"],
		type: "image",
		prompt: "Generate an age transformation sequence showing progression over time",
		gradient: "from-stone-600 to-amber-700",
	},
	{
		id: "before-and-after",
		name: "Before and",
		nameHighlight: "After",
		categories: ["featured", "marketing"],
		type: "image",
		prompt: "Create a compelling before and after comparison image",
		gradient: "from-yellow-700 to-amber-500",
	},
	{
		id: "character-creator",
		name: "Character",
		nameHighlight: "Creator",
		categories: ["featured", "filmmaking"],
		type: "image",
		prompt: "Design a unique character with detailed features and backstory",
		gradient: "from-emerald-700 to-teal-500",
	},
	{
		id: "environmental-transformation",
		name: "Environmental",
		nameHighlight: "Transformation",
		categories: ["featured"],
		type: "image",
		prompt: "Transform an environment between different seasons, times of day, or conditions",
		gradient: "from-orange-700 to-red-500",
	},
	{
		id: "headshot-varieties",
		name: "Headshot",
		nameHighlight: "Varieties",
		categories: ["featured", "branding"],
		type: "image",
		prompt: "Generate professional headshot variations with different styles and backgrounds",
		gradient: "from-slate-700 to-gray-500",
	},
	{
		id: "logo-reveal",
		name: "Logo",
		nameHighlight: "Reveal",
		categories: ["featured", "branding"],
		type: "video",
		prompt: "Create an animated logo reveal with cinematic effects",
		gradient: "from-indigo-700 to-blue-500",
	},
	{
		id: "meme-remixing",
		name: "Meme",
		nameHighlight: "Remixing",
		categories: ["marketing"],
		type: "image",
		prompt: "Remix and reimagine popular meme formats with a fresh creative twist",
		gradient: "from-green-600 to-emerald-400",
	},
	{
		id: "pitch-deck",
		name: "Pitch",
		nameHighlight: "Deck",
		categories: ["branding", "marketing"],
		type: "image",
		prompt: "Design a professional pitch deck with clean layouts and compelling visuals",
		gradient: "from-lime-600 to-green-400",
	},
	{
		id: "product-packaging",
		name: "Product",
		nameHighlight: "Packaging",
		categories: ["product-design", "branding"],
		type: "image",
		prompt: "Design product packaging with premium materials and modern aesthetics",
		gradient: "from-stone-600 to-zinc-400",
	},
	{
		id: "social-media-video-ads",
		name: "Social Media Video",
		nameHighlight: "Ads",
		categories: ["marketing"],
		type: "video",
		prompt: "Create engaging social media video ads optimized for multiple platforms",
		gradient: "from-orange-600 to-yellow-400",
	},
	{
		id: "variants-exploration",
		name: "Variants",
		nameHighlight: "Exploration",
		categories: ["product-design"],
		type: "image",
		prompt: "Explore design variants with different colors, materials, and configurations",
		gradient: "from-purple-600 to-pink-400",
	},
	{
		id: "virtual-models",
		name: "Virtual",
		nameHighlight: "Models",
		categories: ["featured", "filmmaking"],
		type: "image",
		prompt: "Create photorealistic virtual models for fashion and product showcases",
		gradient: "from-sky-700 to-cyan-500",
	},
	{
		id: "cinematography",
		name: "",
		nameHighlight: "Cinematography",
		categories: ["filmmaking"],
		type: "video",
		prompt: "Create cinematic shots with professional camera movements and lighting",
		gradient: "from-teal-700 to-emerald-500",
	},
	{
		id: "manga-creation",
		name: "Manga",
		nameHighlight: "Creation",
		categories: ["filmmaking"],
		type: "image",
		prompt: "Create manga-style illustrations with dynamic panels and expressive characters",
		gradient: "from-slate-600 to-blue-400",
	},
	{
		id: "sketch-to-final",
		name: "Sketch to Final",
		nameHighlight: "Media",
		categories: ["product-design"],
		type: "image",
		prompt: "Transform rough sketches into polished final artwork and media",
		gradient: "from-gray-600 to-slate-400",
	},
	{
		id: "webtoon-creation",
		name: "Webtoon",
		nameHighlight: "Creation",
		categories: ["filmmaking"],
		type: "image",
		prompt: "Create webtoon-style vertical scrolling comic panels with vibrant colors",
		gradient: "from-green-700 to-lime-500",
	},
	{
		id: "brand-identity",
		name: "Brand",
		nameHighlight: "Identity",
		categories: ["branding"],
		type: "image",
		prompt: "Design a complete brand identity including logo, colors, and typography",
		gradient: "from-violet-700 to-purple-500",
	},
	{
		id: "infographics",
		name: "",
		nameHighlight: "Infographics",
		categories: ["marketing", "branding"],
		type: "image",
		prompt: "Create informative and visually appealing infographics with data visualizations",
		gradient: "from-blue-600 to-indigo-400",
	},
	{
		id: "product-photography",
		name: "Product",
		nameHighlight: "Photography",
		categories: ["product-design", "marketing"],
		type: "image",
		prompt: "Generate professional product photography with studio lighting and styling",
		gradient: "from-cyan-700 to-blue-500",
	},
	{
		id: "slide-deck",
		name: "Slide",
		nameHighlight: "Deck",
		categories: ["marketing", "branding"],
		type: "image",
		prompt: "Design a polished slide deck presentation with modern layouts",
		gradient: "from-zinc-700 to-neutral-500",
	},
	{
		id: "trailer",
		name: "",
		nameHighlight: "Trailer",
		categories: ["filmmaking"],
		type: "video",
		prompt: "Create a cinematic trailer with dramatic pacing and visual effects",
		gradient: "from-amber-700 to-yellow-500",
	},
	{
		id: "tiktok-reel",
		name: "TikTok",
		nameHighlight: "Reel",
		categories: ["reels", "featured"],
		type: "video",
		prompt: "Create a viral TikTok reel with trending transitions, auto-captions, and upbeat music. Vertical 9:16 format, 30 seconds",
		gradient: "from-pink-600 to-rose-400",
	},
	{
		id: "youtube-short",
		name: "YouTube",
		nameHighlight: "Short",
		categories: ["reels", "marketing"],
		type: "video",
		prompt: "Create an engaging YouTube Short with hook intro, fast-paced editing, bold captions, and a call to action. Vertical 9:16, 60 seconds",
		gradient: "from-red-600 to-orange-400",
	},
	{
		id: "instagram-reel",
		name: "Instagram",
		nameHighlight: "Reel",
		categories: ["reels", "marketing"],
		type: "video",
		prompt: "Create a polished Instagram Reel with aesthetic transitions, trending audio, and stylish text overlays. Vertical 9:16, 30 seconds",
		gradient: "from-purple-600 to-fuchsia-400",
	},
	{
		id: "product-showcase-reel",
		name: "Product",
		nameHighlight: "Showcase",
		categories: ["reels", "product-design"],
		type: "video",
		prompt: "Create a product showcase reel with smooth 3D rotations, feature callouts, and premium feel. Vertical 9:16, 15 seconds",
		gradient: "from-zinc-600 to-slate-400",
	},
	{
		id: "tutorial-reel",
		name: "Quick",
		nameHighlight: "Tutorial",
		categories: ["reels"],
		type: "video",
		prompt: "Create a step-by-step tutorial reel with numbered steps, clear text overlays, and screen-recording style. Vertical 9:16, 60 seconds",
		gradient: "from-blue-600 to-cyan-400",
	},
];
